#===-- tools/ktest2pcap/Makefile --------------------------*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#

LEVEL=../..
TOOLNAME = ktest2pcap

USEDLIBS = kleeBasic.a
LINK_COMPONENTS = 
NO_PEDANTIC=1

include $(LEVEL)/Makefile.common

LIBS += -lpcap
